name: YouTube Shorts Bot
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  build-and-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install System Dependencies (FFmpeg & ImageMagick)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg imagemagick

      - name: Install Node.js dependencies
        # Pastikan package.json Anda berisi semua dependensi, 
        # atau instal secara eksplisit di sini.
        run: npm install fluent-ffmpeg pexels googleapis @google/generative-ai node-fetch

      - name: Create Authentication Files from Secrets
        run: |
          echo '${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}' > client_secret.json
          echo '${{ secrets.GOOGLE_TOKEN_JSON }}' > token.json

      - name: Jalankan Skrip Utama Bot
        env:
          # --- TAMBAHKAN SECRET LISENSI DI SINI ---
          BOT_LICENSE_EMAIL: ${{ secrets.BOT_LICENSE_EMAIL }}
          
          # Secrets lainnya yang sudah ada
          YT_CHANNEL_NAME: ${{ vars.CHANNEL_NAME }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        run: node bot.js # Menjalankan skrip Node.js Anda

      - name: Simpan Log Baru ke Repositori
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --staged --quiet quotes.txt processed_quotes.log; then
            git add quotes.txt processed_quotes.log
            git commit -m "Bot: Update quotes list and log"
            git push
          else
            echo "No changes to commit in quotes or log."
          fi
