name: YouTube Shorts Bot

on:
  schedule:
    # Menjalankan setiap 2 jam sekali
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build-and-post:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 1. Checkout Repositori
        uses: actions/checkout@v4

      - name: 2. Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg imagemagick

      - name: 4. Install Node.js dependencies
        # Cukup satu perintah ini. Pastikan 'node-fetch' ada di package.json Anda.
        run: npm install

      - name: 5. Create Authentication Files from Secrets
        run: |
          echo '${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}' > client_secret.json
          echo '${{ secrets.GOOGLE_TOKEN_JSON }}' > token.json

      - name: 6. Jalankan Skrip Utama Bot
        env:
          # Ini adalah semua env yang dibutuhkan oleh kode final kita
          BOT_LICENSE_EMAIL: ${{ secrets.BOT_LICENSE_EMAIL }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YT_CHANNEL_NAME: ${{ vars.CHANNEL_NAME }}
        run: node index.js # PERBAIKAN: Perintah 'run' dipindahkan ke posisi yang benar

      - name: 7. Simpan Log Baru ke Repositori
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Cek apakah ada perubahan sebelum mencoba commit
          if ! git diff --quiet --exit-code processed_*.log quotes.txt; then
            git add .
            git commit -m "Bot: Update logs and quote list"
            git push
          else
            echo "No changes to commit."
          fi
          
      - name: 8. Upload Error Screenshot if Job Fails
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot-nodejs
          path: output/error_screenshot.png
          retention-days: 5
